config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  root "pages#home"
  get "user/:id", to: "users#show", as: "user"

  resources :rooms do
    resources :messages
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to room }
  before_create :confirm_participant

  def confirm_participant
    return unless room.is_private

    is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_if_public }
  has_many :messages
  has_many :participants, dependent: :destroy

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]


  scope :all_except, ->(user) { where.not(id: user) }

  after_create_commit { broadcast_append_to "users" }
  has_many :messages

  def self.from_google(u)
    create_with(uid: u[:uid], provider: "google",
                password: Devise.friendly_token[0, 20]).find_or_create_by!(email: u[:email])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end

  private
  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms

    @users = User.all_except(current_user)
    render "index"
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)
    render "index"
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_google(from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:notice] = t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t "devise.omniauth_callbacks.failure", kind: "Google", reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
   end

   def from_google_params
     @from_google_params ||= {
       uid: auth.uid,
       email: auth.info.email
     }
   end

   def auth
     @auth ||= request.env["omniauth.auth"]
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([ @user, current_user ], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    render "rooms/index"
  end

  private

  def get_name(user1, user2)
    user = [ user1, user2 ].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:ring-2 focus:ring-white focus:outline-hidden focus:ring-inset" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <!-- <a href="#" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Dashboard</a> -->
            <!-- <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a> -->

            <% if current_user %>
              <%= link_to "Home", root_path, class: "#{"bg-gray-900" if current_page?(root_path)} rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
              <%= link_to  "Chat Geral", rooms_path, class: "#{"bg-gray-900" if current_page?(rooms_path)} rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center gap-5 pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <% if current_user %>
          <h5 class="text-gray-300"><%= current_user.email %></h5>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "#{"bg-gray-900" if current_page?(new_user_session_path)} rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "#{"bg-gray-900" if current_page?(new_user_registration_path)} rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Dashboard</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
    </div>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form ">
  <%= form_with(model: [@single_room, @message], remote: true, class: 'flex justify-center gap-2', data: { controller: 'input-validation' }) do |f| %>
  <%= f.text_field :body,
      id: 'chat-text',
      class: 'px-5 py-2 border border-gray-200 rounded-sm w-lg transition-all duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-blue-300 focus:border-blue-400 focus:shadow-md',
      autocomplete: 'off',
      data: { input_validation_target: 'input', action: 'input->input-validation#validate' } %>

  <%= f.submit "Enviar",
      id: 'submit-button',
      data: { disable_with: false, action: 'input->input-validation#validate', input_validation_target: 'button' },
      class: 'px-5 py-2 border border-gray-200 rounded-sm text-sm bg-blue-50 transition-all duration-200 ease-in-out active:scale-95 hover:bg-blue-100 hover:border-blue-300 hover:shadow-md disabled:bg-blue-50 disabled:text-gray-400 disabled:cursor-not-allowed' %>
<% end %>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex', data: { controller: 'input-validation' }) do |f| %>
  <%= f.text_field :name,
    class: 'mt-1 p-1 border border-gray-200 rounded-sm focus:outline-none focus:ring-2 focus:ring-blue-300 focus:border-blue-400 sm:text-sm',
    autocomplete: 'off',
    data: { input_validation_target: 'input', action: 'input->input-validation#validate' } %>
  <%= f.submit "Criar",
    data: { disable_with: false },
    class: "px-1 py-1 border border-gray-200 rounded-sm text-sm bg-blue-50 transition-all duration-200 ease-in-out active:scale-95 hover:bg-blue-100 hover:border-blue-300 hover:shadow-md focus:outline-none disabled:bg-blue-50 disabled:text-gray-400 disabled:cursor-not-allowed",
    data: { disable_with: false, action: 'input->input-validation#validate', input_validation_target: 'button' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tecnical Toolz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <style>
      <%= ".msg-#{current_user&.id}" %> {
        background-color: #007bff !important;
        padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end;
      }
    </style>
  </head>

  <body>
    <main>
      <%= render "layouts/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%=message.user.id%>">
  <div class="message-box msg-<%= message.user.id %>">
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.email %> </h6>
    <% end %>
    <%= message.body %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="w-screen h-screen flex items-center justify-center gap-5">
  <h1 class="font-bold text-4xl">Bem vindo a aplicacao!</h1>
  <p>Va para a pagina de Chat geral!</p>
</div>

<% if current_user %>
  <%= link_to  "Start Chatting", rooms_path %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to "Login", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to  room.name, room, class: 'text-blue-500 underline' %>
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="w-full flex ml-12 justify-center gap-16">
  <div id="side_panel" class="mt-8">
    <h4 class="text-2xl">Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4 class="text-2xl mt-5">Salas</h4>
    <%= render 'layouts/new_room_form' %>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms" class="mt-3">
      <%= render @rooms %>
    </div>
  </div>
  <div id="room_container" class="w-2/5 mr-0">
    <% if @single_room %>
      <div id="single_room">
        <h4 class="text-2xl text-center "><%= @user&.email || @single_room.name %></h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages" class="overflow-x-hidden overflow-y-scroll">
          <%= render @messages %>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div>
  <%= link_to user.email, user, class: 'text-blue-500 underline' %>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#show</h1>
  <p>Find me in app/views/users/show.html.erb</p>
</div>